ranking-agent/aragorn-ranker

ranker/logging.yml
ranker/server.py
ranker/shared/cache.py

fixing null key value in response

---

ranker/server.py

syncing all versions of the aragorn services to 1.0.0.

---

ranker/modules/omnicorp_overlay.py

Adding provenance to omnicorp edges

omnicorp prov

---

ranker/modules/omnicorp_overlay.py

Minor update, just making the predicate biolink compatible per Sierra

updated omnicorp predicate

---

ranker/modules/weight_correctness.py
requirements.txt

There was a 500 caused by an unchecked condition where now we were sending in {"attributes": None}

Fixed bug in attribute handling

---

openapi-config.yaml
ranker/modules/omnicorp_overlay.py
ranker/modules/score.py
ranker/modules/weight_correctness.py
ranker/server.py
ranker/shared/util.py
requirements.txt

this upgrades to trapi 1.2.0.4 as well as has some performance updates.

Trapi 1.2.0.4 plus

---

ranker/modules/omnicorp_overlay.py
ranker/modules/score.py
ranker/modules/weight_correctness.py
ranker/shared/util.py

moving to one environment variable for making the timing log event

Timing log

---

ranker/shared/util.py
requirements.txt
tests/InputJson_1.2/treatsSchizophreniaw.json
tests/InputJson_1.2/weighted_answer.json
tests/test_omnicorp_overlay.py
tests/test_ranker.py
tests/test_score.py

i was able to fix all tests with the exception of 2. 
test_nonzero_score(weighted_answer) in test_score.py where score returned is 0. could be a data issue.
test_service(svc_test) in test_ranker.py where an exception is caught when the omnicorp database is being closed.

Test fixes

---

ranker/modules/omnicorp_overlay.py
ranker/modules/score.py
ranker/modules/weight_correctness.py
ranker/server.py

adding logging and logging full exceptions

Err logging

---

ranker/modules/weight_correctness.py
ranker/server.py

krmap, which points from an kg edge id to the edgebindings in results needs to be 1:many, but at some point got changed to be 1:1, breaking things.

fixed another weighting bug

---

ranker/server.py

upping version as a result of r_graph updates

---

ranker/modules/omnicorp_overlay.py
ranker/modules/score.py
ranker/modules/weight_correctness.py
ranker/shared/ranker_obj.py

This adds the weight source into the weight value field. Previously the value field was a number, but is now a dictionary with the origin/primary source as the key. In the creation of the Laplacian matrix, it removes the duplicated sources and takes the max for each edge in the results graph.

Add weight source

---

ranker/shared/ranker_obj.py

There's a case where the recent changes to creating redges fails. It's a multiline comment in the code.
The code now works similarly to before, but edges between nodes with the same qnode_id are removed.

Fixed bug involving creating redges between qnodes bound to multiple knodes

---

ranker/aux/omnicorp_get_node_pmids.py
ranker/aux/omnicorp_shared_pmids.py
ranker/server.py
ranker/shared/omnicorp_postgres.py
ranker/shared/util.py

Similar to getting shared PMIDs.

Add endpoint for getting PMIDs for a single node

---

ranker/modules/weight_correctness.py
ranker/server.py
tests/test_correctness.py

fix improper sigmoid call in weight_correctness

fix weight correctness

---

ranker/server.py
ranker/shared/ranker_obj.py
tests/test_path_collapse.py
tests/test_score.py

This updates the ranking algorithm to no longer use Kirchoff index and produce scores bounded between 0 and 1.

Ranker update

---

ranker/server.py

This bumps the version on Rayn's changes

bump version

---

ranker/shared/ranker_obj.py

Perhaps the name of the branch is poor, but this came about as part of investigation into the speed of the ranker. No significant speed ups were found, but several bugs were identified that led to edges not being included in the ranking. This largely came from additional nodes provided in aux graphs.
This also includes a fix for probe selection when multiple ids are bound to a single qnode.
black has occurred so parsing the diff is tough. Sorry. 
line 359 is a big fix.

Ranker speed investigation - Really bug fixes.

---

ranker/modules/omnicorp_overlay.py
ranker/modules/weight_correctness.py
ranker/shared/ranker_obj.py
ranker/shared/sources.py
requirements.txt
tests/test_score.py

Major overall cleanup of code to improve legibility. Includes extensive commenting to be easier to understand.
Adds base_weights to assign edge weights more specifically depending on edge source.
Adjusts sigmoid used for literature co-occurrence from omnicorp to reduce number of ties. Improves ranking so answers used in automated testing appear higher in results.

Anchor node update

---

ranker/server.py
ranker/shared/ranker_obj.py

Hot fix for when edge attributes are missing some attribute properties.

Bug fix for missing attribute props

---

ranker/shared/ranker_obj.py

Added additional error checking to avoid some crashes that have happened with rare/odd json.

Better handle none properties and stringified numbers

---

ranker/server.py
ranker/shared/ranker_obj.py
ranker/shared/sources.py

Add chemical binding affinity and more p-values

Use more values
